runtime: python37

instance_class: F1

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  SECRET_KEY: "$$key"
  SQLALCHEMY_DATABASE_URI: "postgres+pg8000://postgres:pedalhire@/pedalhire?unix_sock=/cloudsql/cse546-group17:us-central1:cse546sql/.s.PGSQL.5432"
  SUPPORT_EMAIL: "vmaskara@asu.edu"
  SEND_GRID_API_KEY: ""
  ENVIRONMENT: "release"
  VERSION: "1.0"
  SENTRY_DSN_API: ""

handlers:

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
