"""empty message

Revision ID: 16684670ad2b
Revises: d100affc3196
Create Date: 2020-04-25 02:13:58.431365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16684670ad2b'
down_revision = 'd100affc3196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'start_time')
    op.drop_column('orders', 'end_time')
    op.drop_column('schedule', 'start_time')
    op.drop_column('schedule', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('end_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('end_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('start_time', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
