"""empty message

Revision ID: 3ac9eefdc482
Revises: d1c984517eb3
Create Date: 2020-04-23 15:19:57.631633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac9eefdc482'
down_revision = 'd1c984517eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('merchants_first_name_key', 'merchants', type_='unique')
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    op.create_unique_constraint('merchants_first_name_key', 'merchants', ['first_name'])
    # ### end Alembic commands ###
