"""empty message

Revision ID: 3c9b31fcaaba
Revises: be5a45a2f7f2
Create Date: 2020-04-18 14:13:22.348619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9b31fcaaba'
down_revision = 'be5a45a2f7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('latitude', sa.String(length=50), nullable=False))
    op.add_column('merchants', sa.Column('longitude', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'longitude')
    op.drop_column('merchants', 'latitude')
    # ### end Alembic commands ###
