"""empty message

Revision ID: c5d677e55b24
Revises: 
Create Date: 2020-04-23 19:15:17.874785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d677e55b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('role_type', sa.Enum('USER', 'MERCHANT', name='role'), nullable=True))
    op.add_column('merchants', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('merchants_first_name_key', 'merchants', type_='unique')
    op.drop_column('merchants', 'modified_at')
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'modified_at')
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('products', 'modified_at')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_column('users', 'modified_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.add_column('products', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.add_column('orders', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('orders', 'updated_at')
    op.add_column('merchants', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('merchants_first_name_key', 'merchants', ['first_name'])
    op.alter_column('merchants', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('merchants', 'updated_at')
    op.drop_column('login', 'role_type')
    # ### end Alembic commands ###
