"""empty message

Revision ID: d0df9edce68a
Revises: d4be73e1f742
Create Date: 2020-04-23 14:29:45.402479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0df9edce68a'
down_revision = 'd4be73e1f742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login', sa.Column('role_type', sa.Enum('USER', 'MERCHANT', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login', 'role_type')
    # ### end Alembic commands ###
