"""empty message

Revision ID: d100affc3196
Revises: 4aa8ed8cb564
Create Date: 2020-04-25 02:10:35.210827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd100affc3196'
down_revision = '4aa8ed8cb564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login', type_='unique')
    # ### end Alembic commands ###
