"""empty message

Revision ID: d4be73e1f742
Revises: c13933b72da9
Create Date: 2020-04-23 00:34:38.110909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4be73e1f742'
down_revision = 'c13933b72da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'login', ['id'])
    op.add_column('merchants', sa.Column('state', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('latitude', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('longitude', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('merchants', 'state')
    op.drop_constraint(None, 'login', type_='unique')
    # ### end Alembic commands ###
