"""empty message

Revision ID: ec1e64496c46
Revises: f9c998481a20
Create Date: 2020-04-26 11:08:24.143482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec1e64496c46'
down_revision = 'f9c998481a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'days',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=5)),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'days',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=5)),
               nullable=False)
    # ### end Alembic commands ###
